### ISSUE TITLE
Open Hangouts conversations

### ISSUE THREAD

**Issue by RayBenefield** [denysdovhan/inboxer#1]
First of all when I saw this the other day I was very happy, being able to separate out Inbox from the rest of my tabs has been super helpful. Not to mention the additional screen real estate.

Something I noticed was that Hangouts conversations will open in a window as is typical of the interface, but we aren't currently able to start a Hangouts or open previous conversations with the current navigation.

If I have time I'll try to jump in, but this would be my first electron app and I may be a tad disoriented as frontend isn't normally my thing either.

Thank you for setting this up though! :)

**Comment by denysdovhan** [comment]
Thanks for reporting!

The current implementation is kinda rough. It just hides all UI-elements that are not related to Inbox. I'll appreciate if you'll find some time to make this part of the application better 🙏

**Comment by dereckquock** [comment]
you can use shortcuts to bring up Hangouts! just hit `h`

**Comment by jmarino** [comment]
We used to hide the handouts UI elements. Newer version v1.3.2 based on Gmail (not Inbox) does not hide anything.
