### ISSUE TITLE
Would it be possible to implement the "bundled mail" feature of Inbox?

### ISSUE THREAD

**Issue by onefork** [denysdovhan/inboxer#100]
Gmail Inbox was actually a Gmail implementation with Pin, Snooze, Reminders, Bundles, several additional auto labels and a tighter Google assistant API integration.

The most important for me was actually the possibility to bundle and add notes on mails. They really helped a lot to reduce cluttering. The bundling is in essence showing mails with the same label as one item. I think its basic functionality could be emulated in two ways:

1. "Skip inbox" specific labels and insert a "mails in label" count item in the mail list;
2. Just bundle mails in the view with specific labels without "skip inbox".

Would it be possible to have bundling implementation in this project?

Thanks!

Best
Bin

**Comment by jmarino** [comment]
As things stand right now it would be really hard to do that. Inboxer just packages gmail as a desktop app, i.e., it displays the webpage provided by gmail and parses the html for notifications and such. What you suggest requires Inboxer to query gmail about email data (somehow), and then render it itself.

There's been talk of implementing something like this to try to replicate Inbox on top of gmail. However, there has been no progress to this day (see #77, #95, #98). We look forward to your contributions.

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: https://github.com/denysdovhan/inboxer/issues/101

If you still need this project, please, fork the repo.
