### ISSUE TITLE
[Fedora27] Error when starting the app using the AppImage installation

### ISSUE THREAD

**Issue by jonas-jonas** [denysdovhan/inboxer#15]
When I try to open the app using the installation of the AppImage I am getting the following error:
![screenshot from 2018-01-08 13-11-29](https://user-images.githubusercontent.com/5540255/34670297-f1271132-f475-11e7-98e4-288f0d3f7831.png)

Steps to reproduce: 

1.  Download the AppImage, make it executable and execute it
2.  Add it to the Apps in gnome using the prompt of AppImage
3.  Try running it from the apps/add it to your favorites and execute it from the panel

Note: The instance that automatically ran after installation worked fine. 
Using fedora27, x86_64 Linux 4.14.11-300.fc27.x86_64 and gnome.

**Comment by Huluti** [comment]
Same issue with the deb.

**Comment by jonas-jonas** [comment]
I think I traced this back to being a similar issue to #9. It looks like upon closing a running instance of the app the processes are not killed and are still running in the background.

**Comment by jmarino** [comment]
Is this still an issue with latest release?

**Comment by jonas-jonas** [comment]
Personally I don't use Fedora anymore. So I can't tell if it's resolved, but it's certainly not an issue for me anymore. Thanks for your efforts.
