### ISSUE TITLE
Unread messages count should be displayed only if nonzero

### ISSUE THREAD

**Issue by eevleevs** [denysdovhan/inboxer#16]
![image](https://user-images.githubusercontent.com/5012744/34692102-d7027904-f4b6-11e7-91a0-48bec0334425.png) claims attention for nothing

**Comment by denysdovhan** [comment]
Yes, that's a bug. Should be fixed. Thanks for reporting!

**Comment by johnnybui** [comment]
Fixed on [v1.1.2](https://github.com/denysdovhan/inboxer/releases/tag/v1.1.2)
