### ISSUE TITLE
Scrolling bug or feature?

### ISSUE THREAD

**Issue by jelen-dev** [denysdovhan/inboxer#17]
In folders like "done" (but I guess it's in all folders) I can see only todays and last month emails I cannot scroll down to load more content like in the original web app. I don't know if it is a bug or feature but it is very inconvenient.

**Comment by denysdovhan** [comment]
It's a bug. I'm gonna take a look at this. Thanks for reporting!

**Comment by jelen-dev** [comment]
Great, happy to test any update. Forgot to mention, I am using mac os Sierra 10.12

**Comment by kalashnikov** [comment]
I have similar issue - cannot scroll in search result and in macos 10.12.

**Comment by johnnybui** [comment]
Fixed on [v1.1.2](https://github.com/denysdovhan/inboxer/releases/tag/v1.1.2)
