### ISSUE TITLE
Gmail delegated authentication

### ISSUE THREAD

**Issue by ramonhur** [denysdovhan/inboxer#18]
When a delegated authentication authority is used for Gmail (it's an option with GSuite), after entering one's email on the Sign in page in Inboxer, the delegated page for authenticating opens in the default browser for the system, finishing the login process in the default browser, hence rendering Inboxer unusable.
Tested on MacOS 10.11.6 with Inboxer 1.0.0 (1.0.0.46)

**Comment by fcomark** [comment]
Same problem with windows 10 and inboxer 1.0.0. Inboxer unusable in this case.

**Comment by denysdovhan** [comment]
Should be fixed by #10. Will be released ASAP as `v1.0.1`.
