### ISSUE TITLE
Grey screen on launch if no connection - have to close and re-open.

### ISSUE THREAD

**Issue by james-s-w-clark** [denysdovhan/inboxer#20]
Perhaps if Inboxer doesn't get a connection on launch, it doesn't check afterwards (e.g. on opening the window from the taskbar) and the grey box remains.

Connection is actually OK though, because if I restart the app then things load up fine.

![inboxer](https://user-images.githubusercontent.com/12559216/34814665-7773fbae-f6e9-11e7-8084-9582a8ecffa1.png)

edit: added error screenshot.

![inboxererr](https://user-images.githubusercontent.com/12559216/34924539-f873baa8-f9de-11e7-9c38-c55b509c7624.PNG)

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
