### ISSUE TITLE
Can't scroll in message via search result

### ISSUE THREAD

**Issue by lamalamaMark** [denysdovhan/inboxer#23]
When I search a message via de search bar I'm able to fold out/fold in the message but scrolling isn't possible. Probably similar to #17

**Comment by andredealmei** [comment]
I have same issue - cannot scroll in search result and in two computers with Windows 10 x64 RS4 and LTSB x64.

**Comment by denysdovhan** [comment]
This issue should be easy to fix. I don't have enough time to maintain this application since I don't use Inbox anymore. Can anyone investigate this issue and fix this? Any contributions would be highly appreciated.

**Comment by johnnybui** [comment]
Fixed on [v1.1.2](https://github.com/denysdovhan/inboxer/releases/tag/v1.1.2)
