### ISSUE TITLE
No notifications until app is opened

### ISSUE THREAD

**Issue by ghost** [denysdovhan/inboxer#25]
I only get notifications about new emails after I open the app. Why not get notifications while app is in dock unopened?

Inboxer 1.0.1
Electron 1.7.9
darwin x64 17.3.0

**Comment by jmarino** [comment]
Is this still an issue with latest version?

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
