### ISSUE TITLE
No notification, no preference

### ISSUE THREAD

**Issue by Titus2018** [denysdovhan/inboxer#26]
First of all : Bravo ! This is a very good stuff for those who, like me, don't no more have access to gmail inside the company.
I use inboxer-1.0.1 on Windows 7.
I don't have any notification and don't see any preference in the parameters to set something like that.
Regards,
Eric

**Comment by CB9TOIIIA** [comment]
similar

**Comment by denysdovhan** [comment]
@JohnnyBui are you maintaining this project?

**Comment by jmarino** [comment]
Is this still an issue with latest release?

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
