### ISSUE TITLE
"Uncaught exception. Cannot read property name of undefined" when starting inboxer

### ISSUE THREAD

**Issue by jhm-ciberman** [denysdovhan/inboxer#28]
![image](https://user-images.githubusercontent.com/7988351/34969895-ded43264-fa4f-11e7-9208-ee6ab97534df.png)

Steps to reproduce: 
1 - Open inboxer. 
2 - Login.
3 - Close inboxer.
4 - Open inboxer.
5 - The error should be shown. 

Info:
Machine: Windows 10 x64.

**Comment by tuchandra** [comment]
Happens to me as well. FWIW, a workaround is to kill the process in Task Manager and restart it.

**Comment by chrisbbe** [comment]
Happens both on Linux and Windows. At login, i'm redirected to Google Sign In page, after sign in the app just hangs waiting for sign in completion, after a restart, the same message appears.

**Comment by DSigmund** [comment]
Happens for me too. @tuchandra Workaround is working.

**Comment by denysdovhan** [comment]
Thanks for reporting! Should be fixed by #44. Thanks, @JohnnyBui!

Please, update to the version `v1.1.0` :pray:
