### ISSUE TITLE
Inboxer throws and unhandled exception.

### ISSUE THREAD

**Issue by fjrg76-com** [denysdovhan/inboxer#3]
---
Inboxer 0.4.1
Electron 1.7.9
linux x64 4.10.0-40-generic

When the window Close button is pressed, an error message pops out. Please see the atachment.
![captura de pantalla de 2017-11-30 17-03-55](https://user-images.githubusercontent.com/11762398/33459716-b0362968-d5f0-11e7-8c3e-3a31d1de9dce.png)

**Comment by denysdovhan** [comment]
Probably, it's some kind of Linux-specific issue. Let see what I can do with it.

**Comment by denysdovhan** [comment]
The issue is located and fixed for me. Bugfix will be published with other fixes and features in the nearest release. Please, wait.

**Comment by denysdovhan** [comment]
@fjrg76mx check out the latest [`v1.0.0` release](https://github.com/denysdovhan/inboxer/releases/tag/v1.0.0). This issues should be resolved.
