### ISSUE TITLE
Docky

### ISSUE THREAD

**Issue by alabotski** [denysdovhan/inboxer#30]
When I try open inboxer from docky. I get error message

![screenshot from 2018-01-22 14-54-22](https://user-images.githubusercontent.com/439337/35219570-38fa00e6-ff84-11e7-8746-407aebec4617.png)

**Comment by denysdovhan** [comment]
Thanks for reporting! Should be fixed by #44. Thanks, @JohnnyBui!

Please, update to the version `v1.1.0` :pray:
