### ISSUE TITLE
Remove labels filter feature

### ISSUE THREAD

**Issue by evandrocoan** [denysdovhan/inboxer#31]
Can this create email filters which remove labels from emails?

I would use be because I have TODO email label list, and will receive a email with `Merged #...` when task is done. But gmail does not allow to create filters with `#`, then I cannot:

1. Match `Merged #` to trigger the filter
1. After triggering the filder, I cannot remove the label from the TODO list because gmail does not allow filters to remove labels.

For now I am manually remove the TODO labels, but this can be automated?

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
