### ISSUE TITLE
Increase/decrease font size

### ISSUE THREAD

**Issue by miked63017** [denysdovhan/inboxer#33]
Hi,

Thanks for the great app!

Is there currently any way to increase/decrease the font size(like ctrl++/ctrl-- would in a browser)?

I feel old asking this lol, but it would be helpful for when I recline to read my messages :)

Thanks!

**Comment by miked63017** [comment]
#34 created

Didn't realize it was that easy lol, haven't worked with electron much...feel free to move them as you see fit...

**Comment by denysdovhan** [comment]
I'm open to changes, but, please, take a look at my suggestions.

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
