### ISSUE TITLE
Cannot add academic email

### ISSUE THREAD

**Issue by naquiroz** [denysdovhan/inboxer#37]
When trying to add an academic email, I'm redirected to the university login on chrome, but when I login succesfully on the university site, the Inboxer wont update and log in. When I try to reopen it says that ther is an error in main process that name is undefined.

**Comment by rogersmj** [comment]
I have a similar issue with my GSuite for Work account. After entering my email address on the login screen in Inboxer, I get kicked to Chrome to enter my password. After entering my password there, I am logged into Inbox in Chrome, and Inboxer is stuck at the login screen.

The behavior I'm getting is identical to https://github.com/denysdovhan/inboxer/issues/18 but I don't think we're using delegated authority. I do get the prompt about whether my email address is owned my an organization or personally -- maybe that's the screen that's confusing Inboxer?

**Comment by denysdovhan** [comment]
cc @JohnnyBui

**Comment by daroga** [comment]
I'm having a similar problem. Anytime I try to add an account that is a Google Apps domain or one that has Google Authenticator 2-factor, somewhere in the login process it jumps to the web browser rather than Inboxer and thus never finishes.

Am I doing something wrong or are these both known issues? I'm so hoping that Inboxer can replace having tabs open to Inbox in Firefox.

Thanks!

**Comment by harsh183** [comment]
I also have this on Ubuntu 18.04. When I try to log into my academic email (The University of Illinois at Urbana-Champaign which authenticates via shibboleth for reference) it opens to firefox, and just goes there. Like the others above, it freezes on the login screen and I have to quit it. 

I don't mind testing it out again and seeing if any fix works for my case too.

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
