### ISSUE TITLE
Issue with two-factor security key

### ISSUE THREAD

**Issue by ThxAndBye** [denysdovhan/inboxer#4]
Hey,

I use a security key for my Google account so I get the error that "You can only use your Security Keys with Google Chrome."  
No problem so far since I have alternative methods to log-in. But if I click on "Try another way to sign in" it doesn't give me the option to select a alternative (like Google Authenticator) but opens a new tab in Chrome. This is useless since I'm already logged-in in chrome and it doesn't carry over the login to inboxer.  

EDIT: For a workaround:  
- open the dev tools  
- set the user agent to Android  
- login and select "I'm having trouble"  
- select google Authenticator and log-in  
- set user agent back to default setting  
- restart inboxer completely

regards

**Comment by simonkern** [comment]
Had the same issue and fixed it in #10

**Comment by Franzie** [comment]
![google s chrome browser monopoly shame](https://user-images.githubusercontent.com/630660/34648742-4209ee8e-f3a0-11e7-9016-a025ab38b21a.png)
Not directly related to this post. However it seems Google is widening their Monopoly and trying to **force** users into using Chrome as browser.
I use Firefox 57 as default browser and I **CANNOT** use my U2F - FIDO Universal 2nd Factor Authentication USB Hardware stick to log into a Google App like Google Contacts, Google Calendar, etc using Firefox, **no matter what I try** . I can use my U2F Stick for two-factor authentication with anybody else just fine, Facebook etc., but not with Google Apps. 
Google tries to bully me back into the Chrome Pocket, as the attached screen clearly shows.
Google Monopoly - Shame on Them. Find ways to put them out in the cold...

**Comment by denysdovhan** [comment]
Should be fixed by `v1.0.1`.
