### ISSUE TITLE
Would like to contribute to this project

### ISSUE THREAD

**Issue by johnnybui** [denysdovhan/inboxer#42]
Hi denysdovhan,

Congratulations for creating such a beautiful project. It's sad to hear that you don't use Inbox by Gmail anymore. Any reason? It that because of the new redesign upcoming Gmail? BTW, it's my pleasure to contribute to this project in my free time. Looking forward to your feedback. Thank you!

Cheers,
Johnny

**Comment by denysdovhan** [comment]
Hi, @JohnnyBui! Thanks for your interest!

> Any reason? It that because of the new redesign upcoming Gmail?

I have other emails at other services (including corporative ones), so it's more convenient for me to use a native Mail client.

> BTW, it's my pleasure to contribute to this project in my free time.

That's great! Can you, please, try to fix these issues #36, #30, #29, #28, #9? They are duplicates of each other. That will be a good beginning for you and a good sign for me, that you really want to take care of this project.

Please, send a PR and I'll and you as a collaborator.

**Comment by johnnybui** [comment]
Thanks for your feedback. I'll looking to those issues in my free time.

**Comment by denysdovhan** [comment]
@JohnnyBui just invited you as a collaborator! Congratulations!

Now you take a lead on this project, so, please, take this seriously. Ping me if you need any help, credentials or have any questions.

**Comment by denysdovhan** [comment]
As a short roadmap:

* Format code with Prettier
* Add dark theme (or multiple themes). See #39.
* Add custom text size. There is a PR #34, but it's not ready yet.
* Add ability to use as default mail client
* Fix existing issues

**Comment by johnnybui** [comment]
Thank you @denysdovhan
