### ISSUE TITLE
Support for Snap package for Linux

### ISSUE THREAD

**Issue by owais** [denysdovhan/inboxer#5]
This looks great! Thanks for all the effort. It would be great if this was published as a Snap package for Linux desktops so users can get automatic delta updates, rollbacks, extra security (by sandboxing) and beta/dev channels (if you wanted). 

Thanks

**Comment by probonopd** [comment]
You can do all of the above with [AppImage](https://appimage.org/), plus it is a true distribution-independent community project.

**Comment by owais** [comment]
Shouldn't AppImage or any alternative packaging have it's own issue/feature request?

**Comment by probonopd** [comment]
Yes. An AppImage is already available, I was just questioning whether a Snap is needed in addition since the use cases you are describing can also be made work using AppImage.

**Comment by owais** [comment]
I don't know. May be they would. I haven't used app images as I personally use snaps so I requested that.

**Comment by denysdovhan** [comment]
@owais I'm not a Linux user and not familiar with Snap packages. Would be great if you can send a PR or help to implement this 🙏 

P.S: Inboxer is being built with `electron-builder`. Here's what I found in docs [about Span](https://www.electron.build/configuration/snap).

**Comment by owais** [comment]
I've never built a snap package but I'm interested in that. Will try to do it this weekend.

**Comment by denysdovhan** [comment]
@owais great! Waiting for your PR!

**Comment by jmarino** [comment]
Snap support added in v1.3.2 by commit 2a032a7. Thanks to @flexiondotorg.
