### ISSUE TITLE
[feat] cmd+num to switch accounts

### ISSUE THREAD

**Issue by madeleineostoja** [denysdovhan/inboxer#51]
Coming from Boxy and one of the features I quickly missed was a keyboard shortcut to switch between accounts (cmd+1, cmd+2, etc), super handy until (if) a unified inbox ever becomes possible.

**Comment by denysdovhan** [comment]
cc @JohnnyBui

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
