### ISSUE TITLE
[feat] Option to opt-out of tracking

### ISSUE THREAD

**Issue by madeleineostoja** [denysdovhan/inboxer#52]
Understand that it's handy to have analytics running to track usage and user flows, but it's also standard to allow users to opt-out of all analytics/tracking in apps, would be good to add an option to Inboxer for that (though imagine that would require custom app-wide preferences first)

**Comment by denysdovhan** [comment]
cc @JohnnyBui

**Comment by wedi** [comment]
This is especially true since the GDPR came into force on May 25th.

**Comment by jonatandorozco** [comment]
Working on it

**Comment by denysdovhan** [comment]
Closed by #69. Will be released ASAP.
