### ISSUE TITLE
[Feature Request] Register the app as a mail client in Windows so it can be used as default app for mails

### ISSUE THREAD

**Issue by LordLyng** [denysdovhan/inboxer#53]
It would be nice if Inboxer registered itself as an email client in Windows so that it could be used as the default mail app in Windows.

As far as i know the Electron team has fixed the ProtocolHandler vulnerability by now. So it should "only" require registering it as an email protocol handler.

**Comment by johnnybui** [comment]
That feature is on the development list. BTW, thank you for the news. I will take a look at it soon.

**Comment by wedi** [comment]
I guess (hope) this is on the list for the macOS and linux clients as well? 🙃 Then I'll love inboxer even more. :)

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
