### ISSUE TITLE
Can't download attachments on Linux

### ISSUE THREAD

**Issue by alexdor** [denysdovhan/inboxer#57]
I'm using Inboxer version 1.1.2 on an Ubuntu 16.04 machine, whenever I click to download an attachment nothing happens. There is no error in the console but there is the following warning:
```
Resource interpreted as Document but transferred with MIME type application/zip: "https://mail-attachment.googleusercontent.com/attachment........"
```

**Comment by jmarino** [comment]
Did you check if the file shows up in ~/Downloads?
I'm also on linux and when I click to download an attachment it is silently saved under ~/Downloads. There's no indication that anything happened but the file is there.

It'd be a good idea to provide some kind of feedback to indicate that the file was downloaded successfully.

**Comment by jmarino** [comment]
Versions v1.3.1 and v1.2.2 address this issue by displaying a notification on file download.
NOTE: v1.3.1 is based on Gmail while v1.2.2 is based on Inbox (due to disappear at the end of March 2019).

Please reopen if the issue persists for you.
