### ISSUE TITLE
Toolbar UI borked

### ISSUE THREAD

**Issue by madeleineostoja** [denysdovhan/inboxer#58]
Something must have changed in how Inbox styled the user avatar, becuase it now overflows Inboxer's slimmer toolbar. Easy fix would be to just not make the toolbar slimmer, think the web default is fine tbh.

<img width="264" alt="screen shot 2018-07-17 at 4 22 06 pm" src="https://user-images.githubusercontent.com/6374876/42800111-c42fc6da-89dd-11e8-944c-c73e99872277.png">

**Comment by denysdovhan** [comment]
Can you send a PR?

**Comment by walleXD** [comment]
@denysdovhan when do you plan on merging @seaneking fix?

**Comment by denysdovhan** [comment]
@walleXD it makes topbar wider. I'd like to keep it as is.

**Comment by walleXD** [comment]
```css
.gb_Sf>.gb_R {
  height: 70% !important
}
```

@denysdovhan adding this css rule to override the default behavior fixes the issues. What do you think of this fix?

<img width="900" alt="screen shot 2018-08-22 at 2 00 26 am" src="https://user-images.githubusercontent.com/6826840/44445538-4c22a980-a5af-11e8-9f83-1e54656f043a.png">

**Comment by denysdovhan** [comment]
@walleXD cool, LGTM 👍

**Comment by walleXD** [comment]
@denysdovhan I will make a pull request with the fix as soon as get the chance

**Comment by jonatandorozco** [comment]
Hi @walleXD ,

Can you send PR in order to get the issue fixed?

Thanks.

**Comment by denysdovhan** [comment]
Closed by #69.
