### ISSUE TITLE
Reply box gets cut-off when you scroll past a message

### ISSUE THREAD

**Issue by cazzer** [denysdovhan/inboxer#6]
**Issue:** When an email is expanded and the reply area is visible, scrolling below the email cuts-off the reply area:
![inboxer reply scroll issue](https://user-images.githubusercontent.com/2466842/34458627-764777b0-ed8e-11e7-87c9-06888b2b5ca8.gif)
On inbox.google.com, the reply area is attached to the email:
![inbox scroll intended](https://user-images.githubusercontent.com/2466842/34458633-eb2a48dc-ed8e-11e7-9c6b-2ca0bf178041.gif)

Awesome job on this project, by the way! You've done a fantastic job replicating all of the functionality, I'm especially impressed by the multiple-account support.

**Comment by denysdovhan** [comment]
Thanks for reporting! GIF is useful for reproducing a bug! Gonna be fixed.

**Comment by johnnybui** [comment]
Fixed on [v1.1.2](https://github.com/denysdovhan/inboxer/releases/tag/v1.1.2)
