### ISSUE TITLE
Menu Bar Auto-Hidden by default

### ISSUE THREAD

**Issue by maglax** [denysdovhan/inboxer#60]
System: Win10
Version: 1.1.3

Menu Bar does not appear at all, with no way to enable it.

**Comment by maglax** [comment]
The issue is caused by `autoHideMenuBar` in `app/config.js` being set to `true`. By changing to 'false`, the menu bar will load. The user can then disable it from the menu if necessary (how to re-enable it is unknown).  If someone can test this out on their end, it would be much appreciated, as I'm pretty sure this was the fix for me, but I'm not 100% sure.

**Comment by denysdovhan** [comment]
Resolved.
