### ISSUE TITLE
Edit menu has two separators on Linux and Windows systems

### ISSUE THREAD

**Issue by maglax** [denysdovhan/inboxer#61]
System: Windows, Linux
Version 1.1.3

Edit menu has two separators on Linux and Windows systems, between `Select all` and `Show Undread Badge`.

**Comment by maglax** [comment]
The issue is caused by a separator being added on line 469: `submenu: [...editItems,   { type: 'separator' }, ...settingsItems],` and 185:   `{ type: 'separator' },` of `app/menu.js`. Removing the seperator on line 469 should fix the issue on Windows/Linux systems and leave OSx systems unaffected.

**Comment by denysdovhan** [comment]
Resolved.
