### ISSUE TITLE
Duplicate new email notifications

### ISSUE THREAD

**Issue by jmarino** [denysdovhan/inboxer#64]
I'm running inboxer in linux. Often times when I get a new email I receive two different notifications for the new email. 

When the email first arrives it is given a default icon, shortly after it is assigned another icon. If I happen to have inboxer open I can see this icon transition happen. The first (default?) icon seems to always be [this one](https://ssl.gstatic.com/bt/C3341AA7A1A076756462EE2E5CD71C11/avatars/avatar_tile___r2_56.png).

Function `checkUnreads` in file `app/renderer/unreads.js` keeps track of already seen new emails in `seenMessages`. It uses the sender, subject, and avatar information to identify the emails. Since the avatar changes right after receipt, the new email is detected as 2 different ones and we get 2 notifications.

One easy and quick fix is to only use sender and subject to track already seen email. See [this commit](https://github.com/jmarino/inboxer/commit/478c1c2c070f64eef5db786d908304c4b6484ce1) for this fix.

**Comment by cralor** [comment]
Seeing the same

**Comment by jmarino** [comment]
PR #79 fixes this bug.
