### ISSUE TITLE
Missing notification on new email from same sender

### ISSUE THREAD

**Issue by jmarino** [denysdovhan/inboxer#65]
Inboxer fails to generate a new email notification in a very particular situation:
- Alice and I have an email thread going
- Alice sends me a new email in the thread -> a new email notification is generated
- I read Alice's email but don't reply, now I have zero unread emails
- Alice sends me another email in the thread -> NO new email notification is generated!

This is because the latest new email looks like the older email already stored in variable `seenMessages` and the code thinks it's the same email. This problem can be fixed by clearing `seenMessages` when we have no more unread emails. Clearing the variable also ensures that `seenMessages` doesn't grow indefinitely for long running sessions of Inboxer.

**Comment by jmarino** [comment]
See [this branch](https://github.com/jmarino/inboxer/tree/fix/issue-65) for a proposed fix to this issue.

EDIT: the branch linked above is not a good fix to the problem. The variable `seenMessages` won't be reset until all emails are read, so the problem described still persists as long as there is at least 1 unread email in the inbox. A better fix is described in PR #81.

**Comment by denysdovhan** [comment]
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.
