### ISSUE TITLE
Maintain project

### ISSUE THREAD

**Issue by jonatandorozco** [denysdovhan/inboxer#67]
Hi @denysdovhan,

I was looking an Google email client and I found this incredible awesome. I want to maintain this project because I believe this project has a lot of potential. Besides I'm going to use it on my startup so I can spend time on it to get it better.

Thanks for all your work.

I am working on #58 and #52 and #68 

PD: It's my first time maintaining projects on Github so if you could tell how you are doing it I will thank you a lot. Obviously if you accept me as a maintainer :D

**Comment by denysdovhan** [comment]
Thanks, @jonorozcoc! Glad to hear that!

I'll happily merge your PRs. If everything will be all right, I'll definitely add you as a collaborator to this project.

>  if you could tell how you are doing it I will thank you a lot

Sure. Ask here or, if you have any private question, ask at my email: denysdovhan@gmail.com

**Comment by denysdovhan** [comment]
@jonorozcoc thanks for #69 👏

I'll add you as a collaborator. Let me know if you need any additional access.

**Comment by denysdovhan** [comment]
Invited!

**Comment by jonatandorozco** [comment]
Really thanks @denysdovhan . I'm going to make my best to improve this project.

> Sure. Ask here or, if you have any private question

How are you managing releases? Are there no dev, test channels?

**Comment by denysdovhan** [comment]
> How are you managing releases? Are there no dev, test channels?

Everything is pretty straightforward (based of [electron-builder](https://www.electron.build/configuration/publish.html#recommended-github-releases-workflow) flow):

1. Draft a new release. Set the “Tag version” to the value of version in your application package.json, and prefix it with v. “Release title” can be anything you want.
2. Push some commits to `master`. Every CI build will update the artifacts attached to this draft.
3. Once you are done, run `npm version` (with `major`, `minor` or `patch` argument). npm will create a release commit with tag.
4. `git push --follow-tags`.
4. Wait for CI and publish the release.

**Comment by denysdovhan** [comment]
For every feature or bugfix, I usually use PRs. `master` is for the stable code.
