### ISSUE TITLE
What will happen to this application when Inbox dies?

### ISSUE THREAD

**Issue by alaney** [denysdovhan/inboxer#76]
I, like many others, love Inbox and I am very sad to see it go (in March 2019). I'm now on the search for a new email client. This application came up in several searches but I'm wondering what will happen when Inbox goes offline. If you use their services will you suffer the same fate?

**Comment by denysdovhan** [comment]
This client will probably die too. 

However, it depends on what @jonorozcoc will decide about it. I think it's possible to reimplement all Inbox features using Gmail's API.

**Comment by byronigoe** [comment]
I'd be willing to help with development of an "Inbox" clone. I thought this repo was that, until I looked at the source code and saw that it just loads the official website in an Electron wrapper.

**Comment by denysdovhan** [comment]
@byronigoe you're welcome. Ask me if you need something.
