### ISSUE TITLE
Cut off Title Bar

### ISSUE THREAD

**Issue by sapphyrus** [denysdovhan/inboxer#8]
![Image](https://i.imgur.com/Y76hFXR.png)

**Comment by yasinguzel** [comment]
os x app has same problem
![screen shot 2018-01-06 at 19 15 34](https://user-images.githubusercontent.com/16020123/34641510-a1610d20-f316-11e7-8635-5be2525e2222.png)

**Comment by yasinguzel** [comment]
os x app has same problem
![screen shot 2018-01-06 at 19 15 34](https://user-images.githubusercontent.com/16020123/34641580-4d3badf8-f317-11e7-867f-444064c35138.png)

**Comment by waquidvp** [comment]
I am having same issue on Windows.

![inboxer screenshot](https://user-images.githubusercontent.com/15846228/34651452-50ed9c16-f3c8-11e7-8147-e654fc6aa26e.PNG)

**Comment by emamut** [comment]
I have same issue in Ubuntu 17.10

![screenshot from 2018-01-07 13-45-48](https://user-images.githubusercontent.com/134828/34652810-29b5b3fc-f3b1-11e7-8934-4a25a99b69ed.png)

**Comment by aexvir** [comment]
Same issue on macOS High Sierra 10.13.2

**Comment by denysdovhan** [comment]
Needs to be fixed ASAP. Thanks for reporting!

**Comment by denysdovhan** [comment]
Fixed by https://github.com/denysdovhan/inboxer/commit/4eac6d7ac4ca830e7fbaac12c90bbf9204a6ee6b. Will be released as `v1.0.1`
