### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by ZQiannnn** [denysdovhan/inboxer#82]
Is any plan to support mutli-language?

**Comment by denysdovhan** [comment]
I think it's possible. @jonorozcoc what do you think?

**Comment by jonatandorozco** [comment]
Yes, but using Inbox locale strings or making new ones on Inboxer?

**Comment by denysdovhan** [comment]
@jonorozcoc we can do both. Until Inbox goes down we can use locale strings, after that, of course, we need to implement that by ourselves.
