### ISSUE TITLE
[Feature Request] Gsuite Services

### ISSUE THREAD

**Issue by BenIrving** [denysdovhan/inboxer#86]
When using Inbox web, Google provide an option to quickly switch to another Google App (Calendar etc.) 

Would it be possible to add this to the menu bar, and open a browser link to the specified apps?

**Comment by denysdovhan** [comment]
No features planned since Inbox is gonna be closed by Google and Inboxer is not maintained anymore. However, if you need any feature, just send a PR.

**Comment by SafariMonkey** [comment]
> Inboxer is not maintained anymore

What do you mean by that? In a more recent issue you mention the possibility of a Patreon. Are you planning on maintaining this again or is it dead once Inbox disappears?

I'm looking for an alternative to Inbox once it disappears, and I was hoping this might be it if it's implemented on top of Gmail.

**Comment by denysdovhan** [comment]
@SafariMonkey I don't have plans on maintaining it. I simply don't have time for that. @jonorozcoc is now a lead maintainer of this project.

P.S: When I talked about Patreon I meant supporting my other projects, like [Spaceship ZSH](https://github.com/denysdovhan/spaceship-prompt).
