### ISSUE TITLE
Question: I didn't understand if this project is on top of inbox or on top of gmail?

### ISSUE THREAD

**Issue by tomer-ben-david** [denysdovhan/inboxer#90]
I'm asking because next month inbox is shutting down so i want to know if reminders and bundles would exist in this project or not? in addition would you have a web based version of this app so i can access it also from phone and not only from desktop?

**Comment by denysdovhan** [comment]
It's inbox based.
@jmarino did some work on migrating to Gmail. However, I'm not sure if this project will stay alive.
