### ISSUE TITLE
need to add binaries to 1.3.0 release

### ISSUE THREAD

**Issue by jmarino** [denysdovhan/inboxer#92]
@denysdovhan: I just created a new release but I can't generate Windows or Mac binaries on my linux machine. Is there a way to extract them from Travis CI? How do you normally handle releases?

**Comment by core-code** [comment]
binaries are missing for 1.2.2, 1.3.0 and 1.3.1

**Comment by laander** [comment]
@denysdovhan Thanks for your effort with this app!

As other's said, binaries doesn't seem to exist for `1.3.0` and `1.3.1`. I'm installing it via homebrew and it gives me `1.2.1`. Any chance you could generate binaries for the latest version?

**Comment by eah13** [comment]
And/or add build instructions.  Seems like that'd be good to have for contributions anyways - am I missing them?

**Comment by jmarino** [comment]
@eah13 that is a really good idea. I added some instructions on how to build packages from source to the README file.

**Comment by jmarino** [comment]
I finally figured out how to include binaries in releases. I just made releases `v1.3.2` and `v1.2.3` to force building of binaries.

The binaries are built and automatically uploaded by Travis CI, but only if the release is saved as a draft while the build is ongoing. My mistake was that I was publishing releases too fast, before the Travis CI build was complete.
This is what was printed in the Travis CI build log:
```
• GitHub release not created reason=existing type not compatible with publishing type tag=v1.3.1 version=1.3.1 existingType=release publishingType=draft
```
Travis CI was telling me all along that I was doing it wrong.

**Comment by laander** [comment]
@jmarino Awesome, thanks!

Any chance you can publish `v1.3.2` to the brew cask too? 😇

**Comment by core-code** [comment]
if you mark it as 'Latest Release' in GitHub, we'll add it semi-automatically.

**Comment by jmarino** [comment]
I marked release v1.3.2 as 'Latest Release'. Let me know if the release is successfully added to brew cask.

**Comment by core-code** [comment]
inboxer v1.3.2 is now in homebrew-cask

**Comment by laander** [comment]
Awesome, thank you!
