### ISSUE TITLE
Donation failed

### ISSUE THREAD

**Issue by niclas-ahden** [denysdovhan/inboxer#94]
First off: thanks for working on this!

I tried to donate $50 but the payment failed with ["The payment processing error"](https://cl.ly/78a4e28ec332/Image%2525202019-03-10%252520at%2525207.36.36%252520PM.png). While trying to resolve it with LiqPay's support they asked me to send my credit card info over chat 😅🤦‍♂️

I'd happily donate a monthly amount to keep this going. How about that Patreon profile 
 https://github.com/denysdovhan/inboxer/issues/88#issuecomment-446371473, [SALT like Neovim](https://salt.bountysource.com/teams/neovim) or equivalent?

Keep it up!

**Comment by denysdovhan** [comment]
Thanks for your willingness to support! Unfortunately, PayPal doesn't work in Ukraine (🤷‍♂️), so I had to use LiqPay to make donations work.

Alternatively, I have a Patreon page, it's here: patreon.com/denysdovhan

However, I want to close this project. Take a look at the explanation: https://github.com/denysdovhan/inboxer/issues/101

I'll be grateful if you'd support someone else who wants to build a similar project. Thanks!
