### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by ghost** [denysdovhan/inboxer#99]
Hi, I am very new to this... Im trying to install on macOS but cant figure it out... is anyone willing to send some step by step instructions?

**Comment by jmarino** [comment]
Did you see the instructions on the README file?

https://github.com/denysdovhan/inboxer#package-inboxer-from-source

**Comment by ghost** [comment]
I did... But I can't seem to find the .dmg file to install on mac...

**Comment by jmarino** [comment]
I can't test on mac, so I'm flying blind here. You have to extract the sources, go into that folder and run:
```
npm install
npm run dist:mac
```
Inside folder `./dist` you should find these two files:
```
dist/Inboxer-1.3.1.dmg
dist/Inboxer-1.3.1-mac.zip
```
Is this what you're doing? Are those files not there?

**Comment by jmarino** [comment]
I just figured out how to make Travis CI include binaries in a release. You don't need to build from source anymore.
Go ahead and check out our new v1.3.2 for a freshly baked binary.
I'll make a new v1.2.x release with binaries also.

**Comment by ghost** [comment]
Awesome thank you! Im totally clueless when it comes to command line stuff...But I loved inbox and am sad to see it go. Thank you for this project!
